      <strong>Population: </strong>
  <br><strong>Defense: </strong>
  <br><strong>Laws/Crime: </strong>
  <br><strong>Corruption: </strong>
  <br><strong>Military: </strong>
  <br><strong>Resources: </strong>
  <br><strong>Wealth: </strong>
  <br><strong>Behaviour: </strong>
  <br><strong>Religions: </strong>